modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"
issueTrackerURL = "https://github.com/TheDogOfChaos/Crops-N-Cogs-Core/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "${mod_url}"
# logoFile="icon.png"

credits = "Thanks to tterrag1098 for the incredible tool that is Registrate"
authors = "${mod_author}"
description = "The Coremod for Crops 'N Cogs. Because just KubeJS wasn't enough."

[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "gtceu"
mandatory = true
versionRange = "[${gtceu_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "configuration"
mandatory = true
versionRange = "[${configuration_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "jade"
mandatory = false
versionRange = "[11.12.2,)"
ordering = "AFTER"
side = "CLIENT"

