name: Build on push

on:
  push:
    paths-ignore: ['.github/**', '**/*.md']

concurrency:
  group: auto-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SNAPSHOT: true
      GITHUB_TOKEN: ${{ github.token }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Build
        uses: ./.github/actions/build_setup
      - name: Build
        run: ./gradlew build --build-cache --stacktrace
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/*
          if-no-files-found: error
          retention-days: 90
