name: Build on push

on:
  push:
    branches: ['1.20.1', '1.21']
    paths-ignore: ['.github/**', '**/*.md']

concurrency:
  group: auto-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SNAPSHOT: true
      GITHUB_TOKEN: ${{ github.token }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Build
        uses: ./.github/actions/build_setup
      - name: Get Version
        id: ver
        run: echo "version=$(./gradlew -q printVersion)" >> $GITHUB_OUTPUT
      - name: Build
        run: ./gradlew build --build-cache
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/*
          if-no-files-found: error
          retention-days: 90
      - name: Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: ./.github/json/config-latest.json
          fromTag: latest-${{ github.ref_name }}
          toTag: ${{ github.ref }}
          fetchViaCommits: true
          failOnError: false